import { DeviceSigned, DocType, IssuerSigned } from './types';
import { IssuerSignedDocument } from './IssuerSignedDocument';
/**
 * Represents a device signed document.
 *
 * Note: You don't need to instantiate this class.
 * This is the return type of the parser and it will be generated by the DeviceResponse builder.
 */
export declare class DeviceSignedDocument extends IssuerSignedDocument {
    readonly deviceSigned: DeviceSigned;
    constructor(docType: DocType, issuerSigned: IssuerSigned, deviceSigned: DeviceSigned);
    prepare(): Map<string, any>;
    /**
     * Helper method to get the values in a namespace as a JS object.
     *
     * @param {string} namespace - The namespace to add.
     * @returns {Record<string, any>} - The values in the namespace as an object
     */
    getDeviceNameSpace(namespace: string): Record<string, any>;
}
